const   CURLINFO_STRING     = 0x100000,
        CURLINFO_LONG       = 0x200000,
        CURLINFO_DOUBLE     = 0x300000,
        CURLINFO_SLIST      = 0x400000,
        CURLINFO_SOCKET     = 0x500000,
        CURLINFO_MASK       = 0x0fffff,
        CURLINFO_TYPEMASK   = 0xf00000,
      
        OPTTYPE_LONG    = 0,
        OPTTYPE_OBJECTPOINT  = 10000,
        OPTTYPE_FUNCTIONPOINT    = 20000,
        OPTTYPE_OFF_T   = 30000;

var Ref     = require( 'ref' ),
    Struct  = require( 'ref-struct' ),
    //Enum    = require( 'enum' ),
    //CURLINFO    = new Enum( {
    //        CURLINFO_NONE               : 0,
    //        CURLINFO_EFFECTIVE_URL      : CURLINFO_STRING + 1,
    //        CURLINFO_RESPONSE_CODE      : CURLINFO_LONG   + 2,
    //        CURLINFO_TOTAL_TIME         : CURLINFO_DOUBLE + 3,
    //        CURLINFO_NAMELOOKUP_TIME    : CURLINFO_DOUBLE + 4,
    //        CURLINFO_CONNECT_TIME       : CURLINFO_DOUBLE + 5,
    //        CURLINFO_PRETRANSFER_TIME   : CURLINFO_DOUBLE + 6,
    //        CURLINFO_SIZE_UPLOAD        : CURLINFO_DOUBLE + 7,
    //        CURLINFO_SIZE_DOWNLOAD      : CURLINFO_DOUBLE + 8,
    //        CURLINFO_SPEED_DOWNLOAD     : CURLINFO_DOUBLE + 9,
    //        CURLINFO_SPEED_UPLOAD       : CURLINFO_DOUBLE + 10,
    //        CURLINFO_HEADER_SIZE        : CURLINFO_LONG   + 11,
    //        CURLINFO_REQUEST_SIZE       : CURLINFO_LONG   + 12,
    //        CURLINFO_SSL_VERIFYRESULT   : CURLINFO_LONG   + 13,
    //        CURLINFO_FILETIME           : CURLINFO_LONG   + 14,
    //        CURLINFO_CONTENT_LENGTH_DOWNLOAD    : CURLINFO_DOUBLE + 15,
    //        CURLINFO_CONTENT_LENGTH_UPLOAD      : CURLINFO_DOUBLE + 16,
    //        CURLINFO_STARTTRANSFER_TIME     : CURLINFO_DOUBLE + 17,
    //        CURLINFO_CONTENT_TYPE       : CURLINFO_STRING + 18,
    //        CURLINFO_REDIRECT_TIME      : CURLINFO_DOUBLE + 19,
    //        CURLINFO_REDIRECT_COUNT     : CURLINFO_LONG   + 20,
    //        CURLINFO_PRIVATE            : CURLINFO_STRING + 21,
    //        CURLINFO_HTTP_CONNECTCODE   : CURLINFO_LONG   + 22,
    //        CURLINFO_HTTPAUTH_AVAIL     : CURLINFO_LONG   + 23,
    //        CURLINFO_PROXYAUTH_AVAIL    : CURLINFO_LONG   + 24,
    //        CURLINFO_OS_ERRNO           : CURLINFO_LONG   + 25,
    //        CURLINFO_NUM_CONNECTS       : CURLINFO_LONG   + 26,
    //        CURLINFO_SSL_ENGINES        : CURLINFO_SLIST  + 27,
    //        CURLINFO_COOKIELIST         : CURLINFO_SLIST  + 28,
    //        CURLINFO_LASTSOCKET         : CURLINFO_LONG   + 29,
    //        CURLINFO_FTP_ENTRY_PATH     : CURLINFO_STRING + 30,
    //        CURLINFO_REDIRECT_URL       : CURLINFO_STRING + 31,
    //        CURLINFO_PRIMARY_IP         : CURLINFO_STRING + 32,
    //        CURLINFO_APPCONNECT_TIME    : CURLINFO_DOUBLE + 33,
    //        CURLINFO_CERTINFO           : CURLINFO_SLIST  + 34,
    //        CURLINFO_CONDITION_UNMET    : CURLINFO_LONG   + 35,
    //        CURLINFO_RTSP_SESSION_ID    : CURLINFO_STRING + 36,
    //        CURLINFO_RTSP_CLIENT_CSEQ   : CURLINFO_LONG   + 37,
    //        CURLINFO_RTSP_SERVER_CSEQ   : CURLINFO_LONG   + 38,
    //        CURLINFO_RTSP_CSEQ_RECV     : CURLINFO_LONG   + 39,
    //        CURLINFO_PRIMARY_PORT       : CURLINFO_LONG   + 40,
    //        CURLINFO_LOCAL_IP           : CURLINFO_STRING + 41,
    //        CURLINFO_LOCAL_PORT         : CURLINFO_LONG   + 42,
    //        CURLINFO_TLS_SESSION        : CURLINFO_SLIST  + 43,
    //        CURLINFO_ACTIVESOCKET       : CURLINFO_SOCKET + 44,
    //    } ),
    //CURLcode    = new Enum( [
    //      'CURLE_OK',
    //      'CURLE_UNSUPPORTED_PROTOCOL',
    //      'CURLE_FAILED_INIT',
    //      'CURLE_URL_MALFORMAT',
    //      'CURLE_NOT_BUILT_IN',
    //      'CURLE_COULDNT_RESOLVE_PROXY',
    //      'CURLE_COULDNT_RESOLVE_HOST',
    //      'CURLE_COULDNT_CONNECT',
    //      'CURLE_FTP_WEIRD_SERVER_REPLY',
    //      'CURLE_REMOTE_ACCESS_DENIED',
    //      'CURLE_FTP_ACCEPT_FAILED',
    //      'CURLE_FTP_WEIRD_PASS_REPLY',
    //      'CURLE_FTP_ACCEPT_TIMEOUT',
    //      'CURLE_FTP_WEIRD_PASV_REPLY',
    //      'CURLE_FTP_WEIRD_227_FORMAT',
    //      'CURLE_FTP_CANT_GET_HOST',
    //      'CURLE_HTTP2',
    //      'CURLE_FTP_COULDNT_SET_TYPE',
    //      'CURLE_PARTIAL_FILE',
    //      'CURLE_FTP_COULDNT_RETR_FILE',
    //      'CURLE_OBSOLETE20',
    //      'CURLE_QUOTE_ERROR',
    //      'CURLE_HTTP_RETURNED_ERROR',
    //      'CURLE_WRITE_ERROR',
    //      'CURLE_OBSOLETE24',
    //      'CURLE_UPLOAD_FAILED',
    //      'CURLE_READ_ERROR',
    //      'CURLE_OUT_OF_MEMORY',
    //      'CURLE_OPERATION_TIMEDOUT',
    //      'CURLE_OBSOLETE29',
    //      'CURLE_FTP_PORT_FAILED',
    //      'CURLE_FTP_COULDNT_USE_REST',
    //      'CURLE_OBSOLETE32',
    //      'CURLE_RANGE_ERROR',
    //      'CURLE_HTTP_POST_ERROR',
    //      'CURLE_SSL_CONNECT_ERROR',
    //      'CURLE_BAD_DOWNLOAD_RESUME',
    //      'CURLE_FILE_COULDNT_READ_FILE',
    //      'CURLE_LDAP_CANNOT_BIND',
    //      'CURLE_LDAP_SEARCH_FAILED',
    //      'CURLE_OBSOLETE40',
    //      'CURLE_FUNCTION_NOT_FOUND',
    //      'CURLE_ABORTED_BY_CALLBACK',
    //      'CURLE_BAD_FUNCTION_ARGUMENT',
    //      'CURLE_OBSOLETE44',
    //      'CURLE_INTERFACE_FAILED',
    //      'CURLE_OBSOLETE46',
    //      'CURLE_TOO_MANY_REDIRECTS' ,
    //      'CURLE_UNKNOWN_OPTION',
    //      'CURLE_TELNET_OPTION_SYNTAX' ,
    //      'CURLE_OBSOLETE50',
    //      'CURLE_PEER_FAILED_VERIFICATION',
    //      'CURLE_GOT_NOTHING',
    //      'CURLE_SSL_ENGINE_NOTFOUND',
    //      'CURLE_SSL_ENGINE_SETFAILED',
    //      'CURLE_SEND_ERROR',
    //      'CURLE_RECV_ERROR',
    //      'CURLE_OBSOLETE57',
    //      'CURLE_SSL_CERTPROBLEM',
    //      'CURLE_SSL_CIPHER',
    //      'CURLE_SSL_CACERT',
    //      'CURLE_BAD_CONTENT_ENCODING',
    //      'CURLE_LDAP_INVALID_URL',
    //      'CURLE_FILESIZE_EXCEEDED',
    //      'CURLE_USE_SSL_FAILED',
    //      'CURLE_SEND_FAIL_REWIND',
    //      'CURLE_SSL_ENGINE_INITFAILED',
    //      'CURLE_LOGIN_DENIED',
    //      'CURLE_TFTP_NOTFOUND',
    //      'CURLE_TFTP_PERM',
    //      'CURLE_REMOTE_DISK_FULL',
    //      'CURLE_TFTP_ILLEGAL',
    //      'CURLE_TFTP_UNKNOWNID',
    //      'CURLE_REMOTE_FILE_EXISTS',
    //      'CURLE_TFTP_NOSUCHUSER',
    //      'CURLE_CONV_FAILED',
    //      'CURLE_CONV_REQD',
    //      'CURLE_SSL_CACERT_BADFILE',
    //      'CURLE_REMOTE_FILE_NOT_FOUND',
    //      'CURLE_SSH',
    //      'CURLE_SSL_SHUTDOWN_FAILED',
    //      'CURLE_AGAIN',
    //      'CURLE_SSL_CRL_BADFILE',
    //      'CURLE_SSL_ISSUER_ERROR',
    //      'CURLE_FTP_PRET_FAILED',
    //      'CURLE_RTSP_CSEQ_ERROR',
    //      'CURLE_RTSP_SESSION_ERROR',
    //      'CURLE_FTP_BAD_FILE_LIST',
    //      'CURLE_CHUNK_FAILED',
    //      'CURLE_NO_CONNECTION_AVAILABLE',
    //      'CURLE_SSL_PINNEDPUBKEYNOTMATCH',
    //      'CURLE_SSL_INVALIDCERTSTATUS',
    //      'CURL_LAST'
    //] ),
    //CURLoption  = new Enum( {
    //    'WRITEDATA' : OPTTYPE_OBJECTPOINT + 1,
    //    'URL'       : OPTTYPE_OBJECTPOINT + 2,
    //    'PORT'      : OPTTYPE_LONG + 3,
    //    'PROXY'     : OPTTYPE_OBJECTPOINT + 4,
    //    'USERPWD'   : OPTTYPE_OBJECTPOINT + 5,
    //    'PROXYUSERPWD'  : OPTTYPE_OBJECTPOINT + 6,
    //    'RANGE'     : OPTTYPE_OBJECTPOINT + 7,
    //    'READDATA'  : OPTTYPE_OBJECTPOINT + 9,
    //    'ERRORBUFFER'   : OPTTYPE_OBJECTPOINT + 10,
    //    'WRITEFUNCTION' : OPTTYPE_FUNCTIONPOINT + 11,
    //    'READFUNCTION'  : OPTTYPE_FUNCTIONPOINT + 12,
    //    'TIMEOUT'   : OPTTYPE_LONG + 13,
    //    'INFILESIZE'    : OPTTYPE_LONG + 14,
    //    'POSTFIELDS'    : OPTTYPE_OBJECTPOINT + 15,
    //    'REFERER'   : OPTTYPE_OBJECTPOINT + 16,
    //    'FTPPORT'   : OPTTYPE_OBJECTPOINT + 17,
    //    'USERAGENT' : OPTTYPE_OBJECTPOINT + 18,
    //    'LOW_SPEED_LIMIT' : OPTTYPE_LONG + 19,
    //    'LOW_SPEED_TIME'  : OPTTYPE_LONG + 20,
    //    'RESUME_FROM'   : OPTTYPE_LONG + 21,
    //    'COOKIE'    : OPTTYPE_OBJECTPOINT + 22,
    //    'HTTPHEADER'    : OPTTYPE_OBJECTPOINT + 23,
    //    'HTTPPOST'  : OPTTYPE_OBJECTPOINT + 24,
    //    'SSLCERT'   : OPTTYPE_OBJECTPOINT + 25,
    //    'KEYPASSWD' : OPTTYPE_OBJECTPOINT + 26,
    //    'CRLF'      : OPTTYPE_LONG + 27,
    //    'QUOTE'     : OPTTYPE_OBJECTPOINT + 28,
    //    'HEADERDATA'    : OPTTYPE_OBJECTPOINT + 29,
    //    'COOKIEFILE'    : OPTTYPE_OBJECTPOINT + 31,
    //    'SSLVERSION'    :OPTTYPE_LONG + 32,
    //    'TIMECONDITION' :OPTTYPE_LONG + 33,
    //    'TIMEVALUE'     :OPTTYPE_LONG + 34,
    //    'CUSTOMREQUEST' :OPTTYPE_OBJECTPOINT + 36,
    //    'STDERR'    :OPTTYPE_OBJECTPOINT + 37,
    //    'POSTQUOTE' : OPTTYPE_OBJECTPOINT + 39,
    //    'OBSOLETE40'    : OPTTYPE_OBJECTPOINT + 40,
    //    'VERBOSE'   : OPTTYPE_LONG + 41,
    //    'HEADER'    : OPTTYPE_LONG + 42,
    //    'NOPROGRESS'    : OPTTYPE_LONG + 43,
    //    'NOBODY'    : OPTTYPE_LONG + 44,
    //    'FAILONERROR'   : OPTTYPE_LONG + 45,
    //    'UPLOAD'    : OPTTYPE_LONG + 46,
    //    'POST'      : OPTTYPE_LONG + 47,
    //    'DIRLISTONLY'   : OPTTYPE_LONG + 48,
    //    'APPEND'    : OPTTYPE_LONG + 50,
    //    'NETRC'     : OPTTYPE_LONG + 51,
    //    'FOLLOWLOCATION'    : OPTTYPE_LONG + 52,
    //    'TRANSFERTEXT'  : OPTTYPE_LONG + 53,
    //    'PUT'       : OPTTYPE_LONG + 54,
    //    'PROGRESSFUNCTION'  : OPTTYPE_FUNCTIONPOINT + 56,
    //    'PROGRESSDATA'  : OPTTYPE_OBJECTPOINT + 57,
    //    'AUTOREFERER'   : OPTTYPE_LONG + 58,
    //    'PROXYPORT' : OPTTYPE_LONG + 59,
    //    'POSTFIELDSIZE' : OPTTYPE_LONG + 60,
    //    'HTTPPROXYTUNNEL'   : OPTTYPE_LONG + 61,
    //    'INTERFACE'     : OPTTYPE_OBJECTPOINT + 62,
    //    'KRBLEVEL'      : OPTTYPE_OBJECTPOINT + 63,
    //    'SSL_VERIFYPEER'    : OPTTYPE_LONG + 64,
    //    'CAINFO'    : OPTTYPE_OBJECTPOINT + 65,
    //    'MAXREDIRS' : OPTTYPE_LONG + 68,
    //    'FILETIME'  : OPTTYPE_LONG + 69,
    //    'TELNETOPTIONS' : OPTTYPE_OBJECTPOINT + 70,
    //    'MAXCONNECTS'   : OPTTYPE_LONG + 71,
    //    'OBSOLETE72'    : OPTTYPE_LONG + 72,
    //    'FRESH_CONNECT' : OPTTYPE_LONG + 74,
    //    'FORBID_REUSE'  : OPTTYPE_LONG + 75,
    //    'RANDOM_FILE'   : OPTTYPE_OBJECTPOINT + 76,
    //    'EGDSOCKET'     : OPTTYPE_OBJECTPOINT + 77,
    //    'CONNECTTIMEOUT'    : OPTTYPE_LONG + 78,
    //    'HEADERFUNCTION'    : OPTTYPE_FUNCTIONPOINT + 79,
    //    'HTTPGET'   : OPTTYPE_LONG + 80,
    //    'SSL_VERIFYHOST'    : OPTTYPE_LONG + 81,
    //    'COOKIEJAR' : OPTTYPE_OBJECTPOINT + 82,
    //    'SSL_CIPHER_LIST'   : OPTTYPE_OBJECTPOINT + 83,
    //    'HTTP_VERSION'  : OPTTYPE_LONG + 84,
    //    'FTP_USE_EPSV'  : OPTTYPE_LONG + 85,
    //    'SSLCERTTYPE'   : OPTTYPE_OBJECTPOINT + 86,
    //    'SSLKEY'    : OPTTYPE_OBJECTPOINT + 87,
    //    'SSLKEYTYPE'    : OPTTYPE_OBJECTPOINT + 88,
    //    'SSLENGINE'     : OPTTYPE_OBJECTPOINT + 89,
    //    'SSLENGINE_DEFAULT' : OPTTYPE_LONG + 90,
    //    'DNS_USE_GLOBAL_CACHE' : OPTTYPE_LONG + 91,
    //    'DNS_CACHE_TIMEOUT' : OPTTYPE_LONG + 92,
    //    'PREQUOTE' : OPTTYPE_OBJECTPOINT + 93,
    //    'DEBUGFUNCTION' : OPTTYPE_FUNCTIONPOINT + 94,
    //    'DEBUGDATA' : OPTTYPE_OBJECTPOINT + 95,
    //    'COOKIESESSION' : OPTTYPE_LONG + 96,
    //    'CAPATH' : OPTTYPE_OBJECTPOINT + 97,
    //    'BUFFERSIZE' : OPTTYPE_LONG + 98,
    //    'NOSIGNAL' : OPTTYPE_LONG + 99,
    //    'SHARE' : OPTTYPE_OBJECTPOINT + 100,
    //    'PROXYTYPE' : OPTTYPE_LONG + 101,
    //    'ACCEPT_ENCODING' : OPTTYPE_OBJECTPOINT + 102,
    //    'PRIVATE' : OPTTYPE_OBJECTPOINT + 103,
    //    'HTTP200ALIASES' : OPTTYPE_OBJECTPOINT + 104,
    //    'UNRESTRICTED_AUTH' : OPTTYPE_LONG + 105,
    //    'FTP_USE_EPRT' : OPTTYPE_LONG + 106,
    //    'HTTPAUTH' : OPTTYPE_LONG + 107,
    //    'SSL_CTX_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 108,
    //    'SSL_CTX_DATA' : OPTTYPE_OBJECTPOINT + 109,
    //    'FTP_CREATE_MISSING_DIRS' : OPTTYPE_LONG + 110,
    //    'PROXYAUTH' : OPTTYPE_LONG + 111,
    //    'FTP_RESPONSE_TIMEOUT' : OPTTYPE_LONG + 112,
    //    'IPRESOLVE' : OPTTYPE_LONG + 113,
    //    'MAXFILESIZE' : OPTTYPE_LONG + 114,
    //    'INFILESIZE_LARGE' : OPTTYPE_OFF_T + 115,
    //    'RESUME_FROM_LARGE' : OPTTYPE_OFF_T + 116,
    //    'MAXFILESIZE_LARGE' : OPTTYPE_OFF_T + 117,
    //    'NETRC_FILE' : OPTTYPE_OBJECTPOINT + 118,
    //    'USE_SSL' : OPTTYPE_LONG + 119,
    //    'POSTFIELDSIZE_LARGE' : OPTTYPE_OFF_T + 120,
    //    'TCP_NODELAY' : OPTTYPE_LONG + 121,
    //    'FTPSSLAUTH' : OPTTYPE_LONG + 129,
    //    'IOCTLFUNCTION' : OPTTYPE_FUNCTIONPOINT + 130,
    //    'IOCTLDATA' : OPTTYPE_OBJECTPOINT + 131,
    //    'FTP_ACCOUNT' : OPTTYPE_OBJECTPOINT + 134,
    //    'COOKIELIST' : OPTTYPE_OBJECTPOINT + 135,
    //    'IGNORE_CONTENT_LENGTH' : OPTTYPE_LONG + 136,
    //    'FTP_SKIP_PASV_IP' : OPTTYPE_LONG + 137,
    //    'FTP_FILEMETHOD' : OPTTYPE_LONG + 138,
    //    'LOCALPORT' : OPTTYPE_LONG + 139,
    //    'LOCALPORTRANGE' : OPTTYPE_LONG + 140,
    //    'CONNECT_ONLY' : OPTTYPE_LONG + 141,
    //    'CONV_FROM_NETWORK_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 142,
    //    'CONV_TO_NETWORK_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 143,
    //    'CONV_FROM_UTF8_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 144,
    //    'MAX_SEND_SPEED_LARGE' : OPTTYPE_OFF_T + 145,
    //    'MAX_RECV_SPEED_LARGE' : OPTTYPE_OFF_T + 146,
    //    'FTP_ALTERNATIVE_TO_USER' : OPTTYPE_OBJECTPOINT + 147,
    //    'SOCKOPTFUNCTION' : OPTTYPE_FUNCTIONPOINT + 148,
    //    'SOCKOPTDATA' : OPTTYPE_OBJECTPOINT + 149,
    //    'SSL_SESSIONID_CACHE' : OPTTYPE_LONG + 150,
    //    'SSH_AUTH_TYPES' : OPTTYPE_LONG + 151,
    //    'SSH_PUBLIC_KEYFILE' : OPTTYPE_OBJECTPOINT + 152,
    //    'SSH_PRIVATE_KEYFILE' : OPTTYPE_OBJECTPOINT + 153,
    //    'FTP_SSL_CCC' : OPTTYPE_LONG + 154,
    //    'TIMEOUT_MS' : OPTTYPE_LONG + 155,
    //    'CONNECTTIMEOUT_MS' : OPTTYPE_LONG + 156,
    //    'HTTP_TRANSFER_DECODING' : OPTTYPE_LONG + 157,
    //    'HTTP_CONTENT_DECODING' : OPTTYPE_LONG + 158,
    //    'NEW_FILE_PERMS' : OPTTYPE_LONG + 159,
    //    'NEW_DIRECTORY_PERMS' : OPTTYPE_LONG + 160,
    //    'POSTREDIR' : OPTTYPE_LONG + 161,
    //    'SSH_HOST_PUBLIC_KEY_MD5' : OPTTYPE_OBJECTPOINT + 162,
    //    'OPENSOCKETFUNCTION' : OPTTYPE_FUNCTIONPOINT + 163,
    //    'OPENSOCKETDATA' : OPTTYPE_OBJECTPOINT + 164,
    //    'COPYPOSTFIELDS' : OPTTYPE_OBJECTPOINT + 165,
    //    'PROXY_TRANSFER_MODE' : OPTTYPE_LONG + 166,
    //    'SEEKFUNCTION' : OPTTYPE_FUNCTIONPOINT + 167,
    //    'SEEKDATA' : OPTTYPE_OBJECTPOINT + 168,
    //    'CRLFILE' : OPTTYPE_OBJECTPOINT + 169,
    //    'ISSUERCERT' : OPTTYPE_OBJECTPOINT + 170,
    //    'ADDRESS_SCOPE' : OPTTYPE_LONG + 171,
    //    'CERTINFO' : OPTTYPE_LONG + 172,
    //    'USERNAME' : OPTTYPE_OBJECTPOINT + 173,
    //    'PASSWORD' : OPTTYPE_OBJECTPOINT + 174,
    //    'PROXYUSERNAME' : OPTTYPE_OBJECTPOINT + 175,
    //    'PROXYPASSWORD' : OPTTYPE_OBJECTPOINT + 176,
    //    'NOPROXY' : OPTTYPE_OBJECTPOINT + 177,
    //    'TFTP_BLKSIZE' : OPTTYPE_LONG + 178,
    //    'SOCKS5_GSSAPI_SERVICE' : OPTTYPE_OBJECTPOINT + 179,
    //    'SOCKS5_GSSAPI_NEC' : OPTTYPE_LONG + 180,
    //    'PROTOCOLS' : OPTTYPE_LONG + 181,
    //    'REDIR_PROTOCOLS' : OPTTYPE_LONG + 182,
    //    'SSH_KNOWNHOSTS' : OPTTYPE_OBJECTPOINT + 183,
    //    'SSH_KEYFUNCTION' : OPTTYPE_FUNCTIONPOINT + 184,
    //    'SSH_KEYDATA' : OPTTYPE_OBJECTPOINT + 185,
    //    'MAIL_FROM' : OPTTYPE_OBJECTPOINT + 186,
    //    'MAIL_RCPT' : OPTTYPE_OBJECTPOINT + 187,
    //    'FTP_USE_PRET' : OPTTYPE_LONG + 188,
    //    'RTSP_REQUEST' : OPTTYPE_LONG + 189,
    //    'RTSP_SESSION_ID' : OPTTYPE_OBJECTPOINT + 190,
    //    'RTSP_STREAM_URI' : OPTTYPE_OBJECTPOINT + 191,
    //    'RTSP_TRANSPORT' : OPTTYPE_OBJECTPOINT + 192,
    //    'RTSP_CLIENT_CSEQ' : OPTTYPE_LONG + 193,
    //    'RTSP_SERVER_CSEQ' : OPTTYPE_LONG + 194,
    //    'INTERLEAVEDATA' : OPTTYPE_OBJECTPOINT + 195,
    //    'INTERLEAVEFUNCTION' : OPTTYPE_FUNCTIONPOINT + 196,
    //    'WILDCARDMATCH' : OPTTYPE_LONG + 197,
    //    'CHUNK_BGN_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 198,
    //    'CHUNK_END_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 199,
    //    'FNMATCH_FUNCTION' : OPTTYPE_FUNCTIONPOINT + 200,
    //    'CHUNK_DATA' : OPTTYPE_OBJECTPOINT + 201,
    //    'FNMATCH_DATA' : OPTTYPE_OBJECTPOINT + 202,
    //    'RESOLVE' : OPTTYPE_OBJECTPOINT + 203,
    //    'TLSAUTH_USERNAME' : OPTTYPE_OBJECTPOINT + 204,
    //    'TLSAUTH_PASSWORD' : OPTTYPE_OBJECTPOINT + 205,
    //    'TLSAUTH_TYPE' : OPTTYPE_OBJECTPOINT + 206,
    //    'TRANSFER_ENCODING' : OPTTYPE_LONG + 207,
    //    'CLOSESOCKETFUNCTION' : OPTTYPE_FUNCTIONPOINT + 208,
    //    'CLOSESOCKETDATA' : OPTTYPE_OBJECTPOINT + 209,
    //    'GSSAPI_DELEGATION' : OPTTYPE_LONG + 210,
    //    'DNS_SERVERS' : OPTTYPE_OBJECTPOINT + 211,
    //    'ACCEPTTIMEOUT_MS' : OPTTYPE_LONG + 212,
    //    'TCP_KEEPALIVE' : OPTTYPE_LONG + 213,
    //    'TCP_KEEPIDLE' : OPTTYPE_LONG + 214,
    //    'TCP_KEEPINTVL' : OPTTYPE_LONG + 215,
    //    'SSL_OPTIONS' : OPTTYPE_LONG + 216,
    //    'MAIL_AUTH' : OPTTYPE_OBJECTPOINT + 217,
    //    'SASL_IR' : OPTTYPE_LONG + 218,
    //    'XFERINFOFUNCTION' : OPTTYPE_FUNCTIONPOINT + 219,
    //    'XOAUTH2_BEARER' : OPTTYPE_OBJECTPOINT + 220,
    //    'DNS_INTERFACE' : OPTTYPE_OBJECTPOINT + 221,
    //    'DNS_LOCAL_IP4' : OPTTYPE_OBJECTPOINT + 222,
    //    'DNS_LOCAL_IP6' : OPTTYPE_OBJECTPOINT + 223,
    //    'LOGIN_OPTIONS' : OPTTYPE_OBJECTPOINT + 224,
    //    'SSL_ENABLE_NPN' : OPTTYPE_LONG + 225,
    //    'SSL_ENABLE_ALPN' : OPTTYPE_LONG + 226,
    //    'EXPECT_100_TIMEOUT_MS' : OPTTYPE_LONG + 227,
    //    'PROXYHEADER' : OPTTYPE_OBJECTPOINT + 228,
    //    'HEADEROPT' : OPTTYPE_LONG + 229,
    //    'PINNEDPUBLICKEY' : OPTTYPE_OBJECTPOINT + 230,
    //    'UNIX_SOCKET_PATH' : OPTTYPE_OBJECTPOINT + 231,
    //    'SSL_VERIFYSTATUS' : OPTTYPE_LONG + 232,
    //    'SSL_FALSESTART' : OPTTYPE_LONG + 233,
    //    'PATH_AS_IS' : OPTTYPE_LONG + 234,
    //    'PROXY_SERVICE_NAME' : OPTTYPE_OBJECTPOINT + 235,
    //    'SERVICE_NAME' : OPTTYPE_OBJECTPOINT + 236,
    //    'PIPEWAIT' : OPTTYPE_LONG + 237,
    //    'DEFAULT_PROTOCOL' : OPTTYPE_OBJECTPOINT + 238,
    //    'STREAM_WEIGHT' : OPTTYPE_LONG + 239,
    //    'STREAM_DEPENDS' : OPTTYPE_OBJECTPOINT + 240,
    //    'STREAM_DEPENDS_E' : OPTTYPE_OBJECTPOINT + 241,
    //    'CURLOPT_LASTENTRY' : 242
    //} ),
    // Enum is not working with node-ffi
    //CURLversion = new Enum( [
    //    'CURLVERSION_FIRST',
    //    'CURLVERSION_SECOND',
    //    'CURLVERSION_THIRD',
    //    'CURLVERSION_FOURTH',
    //    'CURLVERSION_LAST'
    //] ),
    CURLversion = Ref.types.int,
    CURLoption = Ref.types.int,
    CURLcode = Ref.types.int,
    CURLINFO = Ref.types.int,
    curl_version_info_data = Struct( {
        age         : Ref.types.int,
        version     : Ref.types.CString,
        version_num : Ref.types.int,
        host        : Ref.types.CString,
        features    : Ref.types.int,
        ssl_version : Ref.types.CString,
        ssl_version_num : Ref.types.long,
        libz_version    : Ref.types.CString,
        protocols   : Ref.types.CString,
        ares        : Ref.types.CString,
        ares_num    : Ref.types.int,
        libidn      : Ref.types.CString,
        iconv_ver_num   : Ref.types.int,
        libssh_version  : Ref.types.CString
    } ),

    typedef     = {
            CURLINFO    : Ref.types.int32,
            CURLcode    : Ref.types.int32,
            CURLoption  : Ref.types.int32,
            long        : Ref.types.long,
            time_t      : Ref.types.long
        },
    ptr     = {
        CURL        : Ref.refType( 'void' ),
        curl_httppost : Ref.refType( 'void' ),
        curl_callback : Ref.refType( 'void' ),
        void        : Ref.refType( 'void' ),
        size_t      : Ref.refType( 'size_t' ),
        int         : Ref.refType( 'int' ),
        time_t      : Ref.refType( 'long' ),
        curl_version_info_data  : Ref.refType( curl_version_info_data )
    };

module.exports = {
    CURLINFO    : CURLINFO,
    CURLcode    : CURLcode,
    CURLoptions : CURLoption,
    CURLversion : CURLversion,
    CURLVERSION_NOW : 'CURLVERSION_FOURTH',
    typedef     : typedef,
    ptr         : ptr
};
